pages:
  stage: deploy
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -o https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
  - tar xvzf mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
  - ./mdbook build
  artifacts:
    paths:
    - public
  only:
  - master
