[book]
authors = ["Joep Meindertsma"]
language = "en"
multilingual = false
src = "src"
title = "Argu Docs"

[output.html]
git-repository-url = "https://gitlab.com/ontola/argu-docs"
git-repository-icon = "fa-gitlab"
site-url = "/argu-docs/"
edit-url-template="https://gitlab.com/ontola/argu-docs/-/edit/master/{path}"
additional-css = ["src/assets/styling.css"]

[output.html.fold]
enable = true

[output.linkcheck]
optional=true
warning-policy="ignore"
